[
    {
        "severity": "error",
        "message": "Argument of type \"dict[str, str | int | Decimal | ValueError]\" cannot be assigned to parameter \"Item\" of type \"Mapping[str, TableAttributeValueTypeDef]\" in function \"put_item\"\n\u00a0\u00a0Type \"ValueError\" cannot be assigned to type \"TableAttributeValueTypeDef\"\n\u00a0\u00a0\u00a0\u00a0\"ValueError\" is incompatible with \"bytes\"\n\u00a0\u00a0\u00a0\u00a0\"ValueError\" is incompatible with \"bytearray\"\n\u00a0\u00a0\u00a0\u00a0\"ValueError\" is incompatible with \"str\"\n\u00a0\u00a0\u00a0\u00a0\"ValueError\" is incompatible with \"int\"\n\u00a0\u00a0\u00a0\u00a0\"ValueError\" is incompatible with \"Decimal\"\n\u00a0\u00a0\u00a0\u00a0\"ValueError\" is incompatible with \"bool\"\n\u00a0\u00a0\u00a0\u00a0\"ValueError\" is incompatible with \"Set[int]\"",
        "range": {
            "start": {
                "line": 33,
                "character": 25
            },
            "end": {
                "line": 33,
                "character": 43
            }
        },
        "rule": "reportGeneralTypeIssues"
    },
    {
        "severity": "error",
        "message": "Argument of type \"Literal[123]\" cannot be assigned to parameter \"TableName\" of type \"str\" in function \"list_backups\"\n\u00a0\u00a0\"Literal[123]\" is incompatible with \"str\"",
        "range": {
            "start": {
                "line": 38,
                "character": 38
            },
            "end": {
                "line": 38,
                "character": 41
            }
        },
        "rule": "reportGeneralTypeIssues"
    }
]